// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsJw16X7h0IxI9ro6pzNKxAKWEN7xtQkw',
    appId: '1:1008548802330:web:1c3826acbe0628e4ac06a3',
    messagingSenderId: '1008548802330',
    projectId: 'gemee-shop-app',
    authDomain: 'gemee-shop-app.firebaseapp.com',
    storageBucket: 'gemee-shop-app.appspot.com',
    measurementId: 'G-71X0BWS3VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUv8klU5iAi2nAmdPKooBDJp_9Zt8RTCA',
    appId: '1:1008548802330:android:29512ebe98d806e4ac06a3',
    messagingSenderId: '1008548802330',
    projectId: 'gemee-shop-app',
    storageBucket: 'gemee-shop-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Ayqyvsgs9G4cWp87FZKJftst8-HVXXw',
    appId: '1:1008548802330:ios:57ee33e036604c43ac06a3',
    messagingSenderId: '1008548802330',
    projectId: 'gemee-shop-app',
    storageBucket: 'gemee-shop-app.appspot.com',
    iosBundleId: 'com.example.gemeeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Ayqyvsgs9G4cWp87FZKJftst8-HVXXw',
    appId: '1:1008548802330:ios:6702a884580f2fc5ac06a3',
    messagingSenderId: '1008548802330',
    projectId: 'gemee-shop-app',
    storageBucket: 'gemee-shop-app.appspot.com',
    iosBundleId: 'com.example.gemeeShopApp.RunnerTests',
  );
}
